import React from "react";
import Head from "next/head";
import { BmeButton } from "bme-ui";
import styled from "styled-components";
import { TopBar } from "../../components";
import { Brand, Container } from "../../atoms";

// @TODO: Displayed as a div for now, but should be a main. Looks like a bug in the styled-components that doesnt allow to use main as a styled component.
const StyledMain = styled.div`
  margin-top: 16px;

  @media (min-width: ${({ theme }) => theme.breakpoints.desktop}px) {
    margin-top: 24px;
  }
`;

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <TopBar
      left={<Brand withLink withName />}
      right={
        <>
          <BmeButton size="small">Open app</BmeButton>
        </>
      }
    >
      <TopBar.Item href="/#about">About</TopBar.Item>
      <TopBar.Item href="/#features">Features</TopBar.Item>
      <TopBar.Item href="/#pricing">Pricing</TopBar.Item>
      <TopBar.Item href="/#contact">Contact</TopBar.Item>
    </TopBar>
    <StyledMain>
      <Container>{children}</Container>
    </StyledMain>
  </>
);

export default Layout;
