version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  lint_and_build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Run lint
      - run:
          command: npm run build
          name: Build app

workflows:
  lint:
    jobs:
      - lint_and_build
