import React from "react";
import Head from "next/head";
import styled from "styled-components";
import { useIntl } from "react-intl";
import { Container } from "../../atoms";
import { Footer, SideBar } from "../../components";

// @TODO: Displayed as a div for now, but should be a main. Looks like a bug in the styled-components that doesnt allow to use main as a styled component.
const StyledMain = styled.div`
  margin-top: 16px;

  @media (min-width: ${({ theme }) => theme.breakpoints.desktop}px) {
    margin-top: 24px;
  }
`;

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const intl = useIntl();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SideBar>
        <SideBar.Item icon="grid" label={intl.formatMessage({ id: "layout.app.menu.pets" })} href="/app" />
        <SideBar.Item icon="mail" label={intl.formatMessage({ id: "layout.app.menu.pet_add" })} href="/app/pet/add" />
      </SideBar>
      <StyledMain>
        <Container>{children}</Container>
      </StyledMain>
      <Footer />
    </>
  );
};

export default Layout;
