import "./globals.scss";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import { TopBar } from "@/components";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar
          items={[
            {
              title: "About",
              link: "#",
            },
            {
              title: "Features",
              link: "#",
            },
            {
              title: "Pricing",
              link: "#",
            },
            {
              title: "Contact",
              link: "#",
            },
          ]}
          cta={{
            title: "Download",
            link: "#",
          }}
        />
        {children}
      </body>
    </html>
  );
}
