import type { NextPage } from "next";
import Head from "next/head";
import { DoggoBox, DoggoText } from "../src/ui-components";
import { DoggoTextVariant } from "../src/ui-components/text";
import { SizesEnum } from "../src/settings/sizes";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DoggoBox background="orange" padding={{ x: SizesEnum.ExtraLarge, y: SizesEnum.Large }}>
          <DoggoText variant={DoggoTextVariant.Title1}>Hello hooman!</DoggoText>
          <DoggoText variant={DoggoTextVariant.Title3}>Woof, woof…</DoggoText>
        </DoggoBox>
      </main>
    </div>
  );
};

export default Home;
